// THIS FILE IS AUTO-GENERATED by bin/modules/compile-preset.mjs
// DO NOT EDIT DIRECTLY. Regenerate with `npm run generate`.
// Source: src/presets/essentials-v1.json

export const ESSENTIALS_V1_OPS: ReadonlySet<string> = Object.freeze(new Set<string>([
]));

export const PRESET_VERSIONS: ReadonlyMap<string, ReadonlySet<string>> = new Map([
  ['essentials-v1', ESSENTIALS_V1_OPS],
]);
