// THIS FILE IS AUTO-GENERATED by bin/modules/compile-preset.mjs
// DO NOT EDIT DIRECTLY. Regenerate with `npm run generate`.
// Source: src/presets/essentials-v1.json
//
// Bootstrap stub — overwritten on first `npm run generate` that successfully
// runs the compile-preset step (requires MS365_MCP_FULL_COVERAGE=1 or a
// legacy endpoints.json superset of essentials-v1.ops).
//
// Committed to git per 05-PATTERNS.md:446 so preset evolution diffs stay
// visible in PR reviews without requiring a local regen.

export const ESSENTIALS_V1_OPS: ReadonlySet<string> = Object.freeze(new Set<string>());

export const PRESET_VERSIONS: ReadonlyMap<string, ReadonlySet<string>> = new Map([
  ['essentials-v1', ESSENTIALS_V1_OPS],
]);
